version: "3.8"
services:
  client:
    build: ./CLIENT/web
    ports:
      - "8000:80"
    networks:
      - mern-app
  api-server:
    build: ./API
    ports:
      - "3000:3000"
    networks:
      - mern-app
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - ./data:/data/db
networks:
  mern-app:
    driver: bridge