apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-redis
  namespace: so1p2
  labels:
    app: redis
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: alex4191/my-redis-image:v1.0
          ports:
            - containerPort: 6379  
          resources:
            requests:
              cpu: "0.1" 
              memory: "256Mi"  
            limits:
              cpu: "1"  
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: so1p2
  labels:
    app: redis
spec:
  type: LoadBalancer  
  ports:
    - port: 6379  
      targetPort: 6379  
  selector:
    app: redis