apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  namespace: so1p2
spec:
  selector:
    matchLabels:
      app: consumer
  replicas: 2
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: alex4191/proyecto2-consumer:v1.3
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "256Mi"
            cpu: "0.1"
          limits:
            memory: "512Mi"
            cpu: "0.5"