apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumers
  namespace: so1p2
spec:
  selector:
    matchLabels:
      app: consumers
  replicas: 1
  template:
    metadata:
      labels:
        app: consumers
    spec:
      containers:
      - name: consumers
        image: alex4191/proyecto2-consumer:v3.1
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "256Mi"
            cpu: "0.1"
          limits:
            memory: "512Mi"
            cpu: "0.5"